import Head from 'next/head';
import { useCallback, useRef, useState } from 'react';
import InfiniteScroll from 'react-infinite-scroll-component';
import { useVirtual } from '../lib/react-virtual';

const Infinite = () => {
  const [data, setData] = useState(() => new Array(50).fill());

  const fetchMoreData = () => {
    setTimeout(() => {
      setData((curData) => [...curData, ...new Array(50).fill()]);
    }, 250);
  };

  const hasMore = data.length < 10000;

  const parentRef = useRef();

  const rowVirtualizer = useVirtual({
    size: hasMore ? data.length + 1 : data.length,
    parentRef,
    estimateSize: useCallback(() => 35, []),
    overscan: 1
  });

  return (
    <div>
      <Head>
        <title>Infinite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Infinite</h1>
        <div
          ref={parentRef}
          className="List"
          style={{
            maxHeight: `100vh`,
            width: `100%`,
            overflow: 'auto'
          }}
          id="list"
        >
          <div
            style={{
              height: `${rowVirtualizer.totalSize}px`,
              width: '100%',
              position: 'relative'
            }}
          >
            <InfiniteScroll
              dataLength={data.length}
              next={fetchMoreData}
              hasMore={hasMore}
              loader={<h4>Loading...</h4>}
              scrollableTarget="list"
            >
              {rowVirtualizer.virtualItems.map((virtualRow) => {
                return (
                  <div
                    key={virtualRow.index}
                    className={
                      virtualRow.index % 2 ? 'ListItemOdd' : 'ListItemEven'
                    }
                    style={{
                      // position: 'absolute',
                      // top: 0,
                      // left: 0,
                      // width: '100%',
                      height: `${virtualRow.size}px`
                      // marginTop: `${virtualRow.start}px`
                      // transform: `translateY(${virtualRow.start}px)`
                    }}
                  >
                    Row {virtualRow.index}
                  </div>
                );
              })}
            </InfiniteScroll>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Infinite;
