import Head from 'next/head';

const mockArr = new Array(1000).fill().map((x, index) => index);

export default function Raw() {
  return (
    <div>
      <Head>
        <title>Raw List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Raw List</h1>
        <div
          className="List"
          style={{
            height: `200px`,
            width: `400px`,
            overflow: 'auto'
          }}
        >
          {mockArr.map((item) => {
            return (
              <div
                key={item}
                className={item % 2 ? 'ListItemOdd' : 'ListItemEven'}
                style={{
                  height: 35
                }}
              >
                Row {item}
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
}
